# The first step is responsible for building and tagging the Docker image of our application.
# The second step is responsible for pushing the Docker image built on step one to Container Registry.
# The third step is responsible for deploying the Docker image to Cloud Run, by pointing to the address of the image pushed into Container Registry on step two.
steps:
  - name: gcr.io/cloud-builders/docker
#   We make use of some variables like ${PROJECT_ID} and ${SHORT_SHA}. These are provided by Cloud Build, but, as you can see in Substituting variable values, it’s also possible to provide your own values. That’s the case of ${_SERVICE_NAME}, 
#   a user defined variable we use for managing our generated Docker image, as well as to set the name of the deployed Cloud Run service.
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}",
        "--region",
        "asia-northeast2",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
